### PR TITLE
update version in Readme, increase max number of icons

### PR DESCRIPTION
**Pull request by fabianpage**
Hi for my application i need more icons in the bar (6). In my opinion it still looks very nice with more icons.

### CODE REVIEW

**Comment by fabianpage** [comment]
(And by the way, it's a very nice looking bottom bar)

**Comment by pedromassango** [comment]
Hi @fabianpage thanks to your contribuition. I'm currently following the rules of Material Design and they suggest to have no more than five items in the bar

**Comment by fabianpage** [comment]
@pedromassango Thanks, i really dislike this part of the material design rules ;) Will have these changes in my own repo

**Comment by pedromassango** [comment]
Yes you can have it. Notice that they probably have a reason for that

**Pull request closed without merging**
