### PR TITLE
feat: add customization options

### PR DESCRIPTION
**Pull request by Xazin**
This is the re-implementation of most of the work done on #67 - however with a little bit missing and some optimization to the options.

Let's see if this one can ever be merged. 👍

### CODE REVIEW

**Comment by Xazin** [comment]
@pedromassango How are you doing Pedro?

If you don't have time to maintain this anymore maybe I can help you out? Let me know what you think.

**Review by pedromassango — APPROVED** [review]
LGTM

**Comment by pedromassango** [comment]
> @pedromassango How are you doing Pedro?
> 
> If you don't have time to maintain this anymore maybe I can help you out? Let me know what you think.

Hi that would be great. I can give you access so you can help maintaining this project.

**Comment by Xazin** [comment]
> > @pedromassango How are you doing Pedro?
> > If you don't have time to maintain this anymore maybe I can help you out? Let me know what you think.
> 
> Hi that would be great. I can give you access so you can help maintaining this project.

Sure thing, then I will perform some update/fixes during the coming period so we can release an update soon.

**Pull request merged**
